name: DayZ Voters Tracker

on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos
  workflow_dispatch:

permissions:
  contents: write   # para commitear state.json

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracker
        env:
          DAYZ_SERVER_KEY: ${{ secrets.DAYZ_SERVER_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SERVER_ID: ${{ vars.SERVER_ID }}
        run: |
          python - << 'PY'
          import os
          print("HAS DAYZ_SERVER_KEY:", bool(os.getenv("DAYZ_SERVER_KEY")))
          print("HAS DISCORD_WEBHOOK:", bool(os.getenv("DISCORD_WEBHOOK")))
          PY
                    python dayz_tracker.py

      - name: Persist state.json
        run: |
          if [ -f state.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json
            git commit -m "update state $(date -u +%F-%T)" || echo "no changes"
            git push
          fi
